import React from 'react';
import './App.css';

function App() {

    return (
      <React.Fragment>
        <div>
          <h1 text-align="center">Maze Path Solver</h1>
          <h3>Upload a <b>single</b> maze image below and hit the "start" button to begin processing the image. We will find the shortest path/solution to the maze.</h3>
          <h3>Try downloading and entering a sample file to the right for an example of valid file format.</h3>
          <h3>Refresh the page to start over or reset.</h3>
        </div>
        <div id="wrapper">
          <div id="drop-area">
            <form class="my-form">
              <p >Upload a file with the button below or by dragging and dropping images onto the dashed region</p>
              <input type="file" id="fileElem" accept="image/*" onchange="handleDrop(this.files)"></input>
              <label class="button" id='selectionbutton' for="fileElem">Select a maze/path-tracing file</label>
            </form>
            <div id="gallery" />
            <button class='button' id='solvebutton'>Solve</button> <br></br>
            <canvas id='finalpath'></canvas>
          </div>
          <div id="sample-file-area">
            <form class="my-form-2">
              <p >Here are some sample maze files to play with...</p>
              <b >Download these to test</b>
              <a href="/sample-images/maze1.jpg" download>
                <img src="/sample-images/maze1.jpg" alt="Maze1" width="104" height="104"/>
              </a>
              <br></br>
              <a href="/sample-images/maze2.png" download>
                <img src="/sample-images/maze2.png" alt="Maze2" width="142" height="104"/>
              </a>
              <br></br>
              <a href="/sample-images/maze3.png" download>
                <img src="/sample-images/maze3.png" alt="Maze3" width="104" height="142"/>
              </a>
              <br></br>
            </form>
          </div>
        </div>
        <div>
          <h5 text-align="center">This application was created by Moe Ali, 2019. Utilized tech: Python, React, HTML, CSS, Javascript. Compiled and tested in Visual Studio Code.</h5>
          <h6 text-align="center">Background generated by uiGradients, 2019. Sample maze 2 and 3 provided by Google Images.</h6>
        </div>
      </React.Fragment>
    );

}

export default App;
